const escapeHtml = (value) => String(value ?? "—").replace(/[&<>'"]/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[char]);
const getJson = async (urls, fallback) => { for (const url of urls) { try { const response = await fetch(url); if (response.ok) return response.json(); } catch (_error) { /* tenta fonte estática */ } } return fallback; };

export async function initApmo(apiAvailable = true) {
  const [auditSource, snapshotSource, integritySource] = await Promise.all([getJson(["/api/audit?limit=20", "../data/output/auditoria.json"], []), getJson(["/api/snapshots", "../data/snapshots/index.json"], []), getJson(["/api/integrity"], null)]);
  const audit = Array.isArray(auditSource) ? { entries: auditSource.slice(-20).reverse() } : auditSource;
  const snapshots = Array.isArray(snapshotSource) ? { snapshots: snapshotSource } : snapshotSource;
  const snapshotItems = [...(snapshots.snapshots || [])].sort((a, b) => String(b.timestamp || "").localeCompare(String(a.timestamp || "")));
  const integrity = integritySource || { valid: snapshotItems.length > 0 && snapshotItems.every((item) => item.hashes), checked: snapshotItems.length, message: "Verificação local de metadados" };
  document.getElementById("audit-log").innerHTML = audit.entries.length ? `<div class="table-wrap"><table><thead><tr><th>Data</th><th>Evento</th><th>Operação</th></tr></thead><tbody>${audit.entries.map((entry) => `<tr><td>${escapeHtml(entry.at || entry.timestamp)}</td><td>${escapeHtml(entry.table_name || entry.evento)}</td><td>${escapeHtml(entry.op || entry.detalhes?.status)}</td></tr>`).join("")}</tbody></table></div>` : '<p class="empty-state">Nenhum evento registrado.</p>';
  document.getElementById("snapshot-list").innerHTML = snapshotItems.length ? snapshotItems.map((snapshot) => `<div class="snapshot"><div><strong>${escapeHtml(snapshot.timestamp)}</strong><small>${escapeHtml(snapshot.total_registros)} registros</small></div><button data-restore="${escapeHtml(snapshot.timestamp)}" ${apiAvailable ? "" : "disabled"}>${apiAvailable ? "Restaurar" : "Somente leitura"}</button></div>`).join("") : '<p class="empty-state">Nenhum snapshot disponível.</p>';
  document.getElementById("integrity-status").innerHTML = `<div class="integrity ${integrity.valid ? "good" : "warn"}"><strong>${integrity.valid ? "Íntegra" : "Atenção"}</strong><span>${escapeHtml(integrity.message)} · ${Number(integrity.checked || 0)} verificados</span></div>`;
  document.getElementById("snapshot-compare").innerHTML = snapshotItems.length >= 2 ? `<p>Mais recente: <strong>${escapeHtml(snapshotItems[0].timestamp)}</strong></p><p>Anterior: <strong>${escapeHtml(snapshotItems[1].timestamp)}</strong></p><p class="empty-state">A comparação detalhada será calculada quando os payloads EOV estiverem disponíveis.</p>` : '<p class="empty-state">São necessários dois snapshots.</p>';
  document.getElementById("export-ledger").addEventListener("click", async (event) => { const button = event.currentTarget; const status = document.getElementById("ledger-status"); button.disabled = true; status.textContent = "Gerando exportação verificável…"; try { const ledger = await getJson(["/api/ledger", "../data/output/livro_razao.json"], null); if (!ledger?.manifest) throw new Error("livro-razão indisponível"); const blob = new Blob([JSON.stringify(ledger, null, 2)], { type: "application/json" }); const link = Object.assign(document.createElement("a"), { href: URL.createObjectURL(blob), download: `opera-livro-razao-${new Date().toISOString().slice(0,10)}.json` }); link.click(); URL.revokeObjectURL(link.href); status.textContent = `${ledger.manifest.entries} entradas · raiz ${String(ledger.manifest.root_hash || "vazia").slice(0,12)}`; } catch (error) { status.textContent = error.message; } finally { button.disabled = false; } });
  if (apiAvailable) document.querySelectorAll("[data-restore]").forEach((button) => button.addEventListener("click", async () => { if (!window.confirm(`Restaurar o snapshot ${button.dataset.restore}?`)) return; button.disabled = true; const response = await fetch(`/api/restore?timestamp=${encodeURIComponent(button.dataset.restore)}`, { method: "POST" }); const result = await response.json(); button.textContent = response.ok ? "Restaurado" : result.error || "Falhou"; }));
}
