const escapeHtml = (value) => String(value ?? "—").replace(/[&<>'"]/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[char]);

export class DataTable {
  constructor(target, pagination, rows = []) { this.target = target; this.pagination = pagination; this.rows = rows; this.page = 1; this.pageSize = 20; this.query = ""; this.zone = ""; this.sort = { key: "", direction: 1 }; }
  filtered() { const query = this.query.toLocaleLowerCase("pt-BR"); return this.rows.filter((row) => (!query || JSON.stringify(row).toLocaleLowerCase("pt-BR").includes(query)) && (!this.zone || [row.zona, row.sigla, row.tipo].includes(this.zone))).sort((a, b) => this.sort.key ? String(a[this.sort.key] ?? "").localeCompare(String(b[this.sort.key] ?? ""), "pt-BR", { numeric: true }) * this.sort.direction : 0); }
  render() { const rows = this.filtered(); const columns = [...new Set(this.rows.flatMap(Object.keys))].slice(0, 12); const pages = Math.max(Math.ceil(rows.length / this.pageSize), 1); this.page = Math.min(this.page, pages); const visible = rows.slice((this.page - 1) * this.pageSize, this.page * this.pageSize); this.target.innerHTML = visible.length ? `<div class="table-wrap"><table><thead><tr>${columns.map((column) => `<th><button data-sort="${escapeHtml(column)}">${escapeHtml(column)}${this.sort.key === column ? (this.sort.direction > 0 ? " ↑" : " ↓") : ""}</button></th>`).join("")}</tr></thead><tbody>${visible.map((row) => `<tr>${columns.map((column) => `<td>${escapeHtml(row[column])}</td>`).join("")}</tr>`).join("")}</tbody></table></div>` : '<p class="empty-state">Nenhum registro disponível.</p>'; this.target.querySelectorAll("[data-sort]").forEach((button) => button.addEventListener("click", () => { const key = button.dataset.sort; this.sort.direction = this.sort.key === key ? -this.sort.direction : 1; this.sort.key = key; this.render(); })); this.pagination.innerHTML = `<button ${this.page === 1 ? "disabled" : ""} data-page="prev">Anterior</button><span>${this.page} / ${pages} · ${rows.length} registros</span><button ${this.page === pages ? "disabled" : ""} data-page="next">Próxima</button>`; this.pagination.querySelectorAll("button").forEach((button) => button.addEventListener("click", () => { this.page += button.dataset.page === "next" ? 1 : -1; this.render(); })); }
  setQuery(value) { this.query = value; this.page = 1; this.render(); } setZone(value) { this.zone = value; this.page = 1; this.render(); }
  exportCsv() { const rows = this.filtered(); if (!rows.length) return; const columns = [...new Set(rows.flatMap(Object.keys))]; const quote = (value) => `"${String(value ?? "").replaceAll('"', '""')}"`; const csv = [columns.map(quote).join(";"), ...rows.map((row) => columns.map((column) => quote(row[column])).join(";"))].join("\r\n"); const link = Object.assign(document.createElement("a"), { href: URL.createObjectURL(new Blob(["\uFEFF", csv], { type: "text/csv;charset=utf-8" })), download: "opera-territorial.csv" }); link.click(); URL.revokeObjectURL(link.href); }
}
