const escapeHtml = (value) => String(value ?? "").replace(/[&<>'"]/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[char]);

export function parseCsv(text) {
  const delimiter = text.split(/\r?\n/, 1)[0].split(";").length > text.split(/\r?\n/, 1)[0].split(",").length ? ";" : ",";
  const rows = []; let row = []; let field = ""; let quoted = false;
  for (let index = 0; index < text.length; index += 1) { const char = text[index]; const next = text[index + 1]; if (char === '"' && quoted && next === '"') { field += '"'; index += 1; } else if (char === '"') quoted = !quoted; else if (char === delimiter && !quoted) { row.push(field.trim()); field = ""; } else if ((char === "\n" || char === "\r") && !quoted) { if (char === "\r" && next === "\n") index += 1; row.push(field.trim()); if (row.some(Boolean)) rows.push(row); row = []; field = ""; } else field += char; }
  if (field || row.length) { row.push(field.trim()); rows.push(row); } const headers = (rows.shift() || []).map((header) => header.replace(/^\uFEFF/, "").trim());
  if (!headers.length || headers.some((header) => !header)) throw new Error("Cabeçalho ausente ou inválido");
  return rows.map((values, rowIndex) => { if (values.length !== headers.length) throw new Error(`Linha ${rowIndex + 2}: esperado ${headers.length} campos, encontrado ${values.length}`); return Object.fromEntries(headers.map((header, index) => [header, values[index]])); });
}

export function initUpload({ dropzone, input, preview, feedback, submit, apiAvailable = true }) {
  let records = [];
  const show = (message, type = "info") => { feedback.className = `feedback ${type}`; feedback.textContent = message; };
  const process = async (file) => { if (!file || !file.name.toLowerCase().endsWith(".csv")) { show("Selecione um arquivo .csv", "error"); return; } if (file.size > 5 * 1024 * 1024) { show("O arquivo excede 5 MB", "error"); return; } try { const bytes = await file.arrayBuffer(); let text = new TextDecoder("utf-8", { fatal: true }).decode(bytes); try { records = parseCsv(text); } catch (error) { if (!String(error.message).includes("Linha")) throw error; text = new TextDecoder("windows-1252").decode(bytes); records = parseCsv(text); } if (!records.length) throw new Error("O arquivo não contém registros"); const columns = Object.keys(records[0]); preview.innerHTML = `<p>${records.length} registros · ${columns.length} colunas</p><div class="table-wrap"><table><thead><tr>${columns.map((column) => `<th>${escapeHtml(column)}</th>`).join("")}</tr></thead><tbody>${records.slice(0, 10).map((row) => `<tr>${columns.map((column) => `<td>${escapeHtml(row[column])}</td>`).join("")}</tr>`).join("")}</tbody></table></div>`; submit.disabled = false; show("Arquivo validado. Confira a prévia antes de enviar.", "success"); } catch (error) { records = []; submit.disabled = true; preview.innerHTML = ""; show(error.message, "error"); } };
  dropzone.addEventListener("click", () => input.click()); dropzone.addEventListener("keydown", (event) => { if (["Enter", " "].includes(event.key)) input.click(); }); input.addEventListener("change", () => process(input.files[0])); ["dragenter", "dragover"].forEach((name) => dropzone.addEventListener(name, (event) => { event.preventDefault(); dropzone.classList.add("dragover"); })); ["dragleave", "drop"].forEach((name) => dropzone.addEventListener(name, (event) => { event.preventDefault(); dropzone.classList.remove("dragover"); })); dropzone.addEventListener("drop", (event) => process(event.dataTransfer.files[0]));
  if (!apiAvailable) submit.textContent = "Baixar lote validado";
  submit.addEventListener("click", async () => { submit.disabled = true; try { if (!apiAvailable) { const documentData = { metadata: { origem: "csv_frontend", gerado_em: new Date().toISOString(), total: records.length }, dados: records }; const link = Object.assign(document.createElement("a"), { href: URL.createObjectURL(new Blob([JSON.stringify(documentData, null, 2)], { type: "application/json" })), download: "opera-lote-validado.json" }); link.click(); URL.revokeObjectURL(link.href); show("Lote validado preparado localmente. Nenhum dado foi enviado.", "success"); return; } const response = await fetch("/api/import", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ dados: records, origem: "csv_frontend" }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "Falha na importação"); show(`${result.message}. SHA-256: ${result.sha256.slice(0, 12)}…`, "success"); } catch (error) { show(error.message, "error"); } finally { submit.disabled = false; } });
}
