/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OperadorRouteImport } from './routes/operador'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicCronIngestDiarioGoianiaRouteImport } from './routes/api/public/cron/ingest-diario-goiania'

const OperadorRoute = OperadorRouteImport.update({
  id: '/operador',
  path: '/operador',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronIngestDiarioGoianiaRoute =
  ApiPublicCronIngestDiarioGoianiaRouteImport.update({
    id: '/api/public/cron/ingest-diario-goiania',
    path: '/api/public/cron/ingest-diario-goiania',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/operador': typeof OperadorRoute
  '/api/public/cron/ingest-diario-goiania': typeof ApiPublicCronIngestDiarioGoianiaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/operador': typeof OperadorRoute
  '/api/public/cron/ingest-diario-goiania': typeof ApiPublicCronIngestDiarioGoianiaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/operador': typeof OperadorRoute
  '/api/public/cron/ingest-diario-goiania': typeof ApiPublicCronIngestDiarioGoianiaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/operador'
    | '/api/public/cron/ingest-diario-goiania'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/operador' | '/api/public/cron/ingest-diario-goiania'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/operador'
    | '/api/public/cron/ingest-diario-goiania'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  OperadorRoute: typeof OperadorRoute
  ApiPublicCronIngestDiarioGoianiaRoute: typeof ApiPublicCronIngestDiarioGoianiaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/operador': {
      id: '/operador'
      path: '/operador'
      fullPath: '/operador'
      preLoaderRoute: typeof OperadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/ingest-diario-goiania': {
      id: '/api/public/cron/ingest-diario-goiania'
      path: '/api/public/cron/ingest-diario-goiania'
      fullPath: '/api/public/cron/ingest-diario-goiania'
      preLoaderRoute: typeof ApiPublicCronIngestDiarioGoianiaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  OperadorRoute: OperadorRoute,
  ApiPublicCronIngestDiarioGoianiaRoute: ApiPublicCronIngestDiarioGoianiaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
